# MySQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Connection Pool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.idle-timeout=300000

# JPA - safe for prod
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Logging - errors only
logging.level.root=ERROR
logging.level.com.basic.candidateform=INFO
logging.file.name=logs/candidate-app.log